destinationServer: ''
argoProjectNamespace: ''
argoNamespace: ''


labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
# All helm parameters can be sent by IaC code (Terraform or CDK)
  apps:
    ecsdemoFrontend:
      createProject: true
      #repoURL: git@github.com:aws-containers/ecsdemo-frontend.git
      repoURL: https://github.com/aws-containers/ecsdemo-frontend.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-frontend
      helm:
        values: |-
          ingress:
            enabled: true
            annotations:
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/tags: Environment=dev,Team=ecsdemo-frontend
              alb.ingress.kubernetes.io/target-type: ip
            className: alb
            hosts:
              - paths:
                  - path: /
                    pathType: Prefix
    ecsdemoNodejs:
      createProject: true
      repoURL: https://github.com/aws-containers/ecsdemo-nodejs.git
      #repoURL: git@github.com:aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
      helm:
        parameters:
        - name: replicaCount
          value: '3'
    ecsdemoCrystal:
      createProject: true
      repoURL: https://github.com/aws-containers/ecsdemo-crystal.git
      #repoURL: git@github.com:aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal
      helm:
        parameters:
        - name: replicaCount
          value: '3'
    game2048:
      createProject: true
      repoURL: https://github.com/aws-containers/ecsdemo-crystal.git
      #repoURL: git@github.com:aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal
      helm:
        parameters:
        - name: replicaCount
          value: '3'